In [1]:
list=[1,2,3]
list*2

[1, 2, 3, 1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3])

In [4]:
arr*2

array([2, 4, 6])

In [5]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
matrix_one=np.array(my_matrix)
matrix_one

In [7]:
my_tuple=(1,2,3)
my_tuple

(1, 2, 3)

In [9]:
my_array=np.array(my_tuple)
my_array,type(my_array)

(array([1, 2, 3]), numpy.ndarray)

# Initializing arrays,zeros,ones,Identity,Full Number,Rand,Randint,Randn

In [10]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# 1s matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# any fixed valued matrix
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [22]:
# random decimal number
np.random.rand(2,4)

array([[0.2399516 , 0.14147925, 0.11976292, 0.55749295],
       [0.69300268, 0.16887445, 0.91893315, 0.99007721]])

In [23]:
np.random.randint(1,100,10)

array([57, 91, 34, 85, 99, 66, 39, 37, 13, 57])

In [24]:
np.random.randint(-4,8,size=(3,3))

array([[-4,  3,  4],
       [-2, -1, -1],
       [-2, -4,  2]])

In [25]:
np.random.randn(20)

array([ 0.83845901, -2.57000625, -0.51194664,  0.22395511,  0.82553344,
       -0.31636731,  1.46335833,  0.24562859, -1.30155049,  0.47696117,
        0.51073911, -0.36148532, -0.09885152, -0.34801185,  0.20705764,
        0.45601022,  0.33613761, -0.95184845,  1.06501768,  1.05181668])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#arange()
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [32]:
np.arange(0,4.5,dtype=float)

array([0., 1., 2., 3., 4.])

In [33]:
np.linspace(1,2,100)

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [35]:
np.linspace(4,9,10,retstep=True)

(array([4.        , 4.55555556, 5.11111111, 5.66666667, 6.22222222,
        6.77777778, 7.33333333, 7.88888889, 8.44444444, 9.        ]),
 0.5555555555555556)