In [1]:
list=[1,2,3]
list*2

[1, 2, 3, 1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3])

In [4]:
arr*2

array([2, 4, 6])

In [5]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
matrix_one=np.array(my_matrix)
matrix_one

In [7]:
my_tuple=(1,2,3)
my_tuple

(1, 2, 3)

In [9]:
my_array=np.array(my_tuple)
my_array,type(my_array)

(array([1, 2, 3]), numpy.ndarray)

# Initializing arrays,zeros,ones,Identity,Full Number,Rand,Randint,Randn

In [10]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# 1s matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# any fixed valued matrix
np.full((2,3),5)

In [ ]:
# random decimal number
np.random.rand(2,4)

In [10]:
np.random.randint(1,100,10)

array([24, 27, 83, 94, 74, 95, 24, 81, 15, 18], dtype=int32)

In [ ]:
np.random.randint(-4,8,size=(3,3))

In [ ]:
np.random.randn(20)

In [ ]:
np.eye(5)

In [ ]:
np.identity(5)

In [ ]:
#arange()
np.arange(10)

In [ ]:
np.arange(1,10)

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [5]:
import numpy as np
np.arange(0,4.5,dtype=float)

array([0., 1., 2., 3., 4.])

In [ ]:
np.linspace(1,2,100)

In [6]:
np.linspace(4,9,10,retstep=True)

(array([4.        , 4.55555556, 5.11111111, 5.66666667, 6.22222222,
        6.77777778, 7.33333333, 7.88888889, 8.44444444, 9.        ]),
 np.float64(0.5555555555555556))