# NumPy
NumPy Stand for --Numerical Python

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

list=[1,2,'a',3](can have defferent data type)
numpy array=[1,2,3](same data type)

In [4]:
list=[1,2,4]

In [5]:
list*2

[1, 2, 4, 1, 2, 4]

In [6]:
arr=np.array([1,3,4])
arr*2

array([2, 6, 8])

# Creating NumPy array 
from python data type(e.g list,tuple)

In [7]:
#Let's create a list
my_list=[2,3,6]
my_list

[2, 3, 6]

In [8]:
my_array=np.array(my_list)
my_array

array([2, 3, 6])

In [11]:
my_array[0]+ my_array[1]

5

In [12]:
my_array*2

array([ 4,  6, 12])

In [17]:
my_array/2

array([1. , 1.5, 3. ])

In [18]:
my_array+my_array+my_array

array([ 6,  9, 18])

In [19]:
my_array[0]=11
my_array

array([11,  3,  6])

In [20]:
#Let's create and cast a list of list to generate a 2-D array
my_matrix=[[1,20,3],[4,27,6],[7,17,9],[11,12,13]]
my_matrix

[[1, 20, 3], [4, 27, 6], [7, 17, 9], [11, 12, 13]]

In [21]:
my_matrix_2=np.array(my_matrix)
my_matrix_2

array([[ 1, 20,  3],
       [ 4, 27,  6],
       [ 7, 17,  9],
       [11, 12, 13]])

In [25]:
#Lets a create a tuple
my_tuple=(1,3,5,6)
my_tuple

(1, 3, 5, 6)

In [26]:
my_tuple2=np.array(my_tuple)
my_tuple2


array([1, 3, 5, 6])

In [28]:
my_tuple3=((1,2,3),(4,5,6),(7,8,9))
my_tuple

(1, 3, 5, 6)

In [29]:
my_tuple4=np.array(my_tuple3)
my_tuple4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
my_array=np.array([1,2,3,'a'])
my_array

array(['1', '2', '3', 'a'], dtype='<U11')