In [1]:
list=[1,2,3]
list*2

[1, 2, 3, 1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3])

In [4]:
arr*2

array([2, 4, 6])

In [5]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
matrix_one=np.array(my_matrix)
matrix_one

In [7]:
my_tuple=(1,2,3)
my_tuple

(1, 2, 3)

In [9]:
my_array=np.array(my_tuple)
my_array,type(my_array)

(array([1, 2, 3]), numpy.ndarray)

# Initializing arrays,zeros,ones,Identity,Full Number,Rand,Randint,Randn

In [10]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# 1s matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# any fixed valued matrix
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [22]:
# random decimal number
np.random.rand(2,4)

array([[0.2399516 , 0.14147925, 0.11976292, 0.55749295],
       [0.69300268, 0.16887445, 0.91893315, 0.99007721]])

In [23]:
np.random.randint(1,100,10)

array([57, 91, 34, 85, 99, 66, 39, 37, 13, 57])

In [24]:
np.random.randint(-4,8,size=(3,3))

array([[-4,  3,  4],
       [-2, -1, -1],
       [-2, -4,  2]])

In [25]:
np.random.randn(20)

array([ 0.83845901, -2.57000625, -0.51194664,  0.22395511,  0.82553344,
       -0.31636731,  1.46335833,  0.24562859, -1.30155049,  0.47696117,
        0.51073911, -0.36148532, -0.09885152, -0.34801185,  0.20705764,
        0.45601022,  0.33613761, -0.95184845,  1.06501768,  1.05181668])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Indexing & slicing 2-D array

In [3]:
import numpy as np
np_2d=np.arange(24)
np_2d.shape=(6,4)
np_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
np_2d[2] #to get row 3

array([ 8,  9, 10, 11])

In [5]:
np_2d[2][2] #to get specific element

10

In [6]:
np_2d[-2] 

array([16, 17, 18, 19])

In [7]:
np_2d[2][2]=12 # change value 

In [8]:
np_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 12, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
np_2d[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
np_2d[:-1]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 12, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
np_2d[-1:]

array([[20, 21, 22, 23]])

In [12]:
np_2d[0:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 12, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
np_2d[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 12, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
np_2d[:-2]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 12, 11],
       [12, 13, 14, 15]])

In [15]:
np_2d[2:4] #will print row 2,3

array([[ 8,  9, 12, 11],
       [12, 13, 14, 15]])

In [16]:
np_2d[:2,:2]

array([[0, 1],
       [4, 5]])

In [17]:
np_2d[:1,:]

array([[0, 1, 2, 3]])

In [18]:
np_2d[:,:1]

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20]])

In [19]:
np_2d[:,2:3]

array([[ 2],
       [ 6],
       [12],
       [14],
       [18],
       [22]])

# 1-D array

In [20]:
array_1d=np.array([1,5,7,4,3,2,9,77,45,33])

In [21]:
array_1d[2]

7

In [22]:
array_1d[:3]

array([1, 5, 7])

In [28]:
matrix=[[1,3,5],[2,8,6],[11,5,67],[7,8,5]]
array_2d=np.array(matrix)
array_2d

array([[ 1,  3,  5],
       [ 2,  8,  6],
       [11,  5, 67],
       [ 7,  8,  5]])

In [29]:
array_1d[::]

array([ 1,  5,  7,  4,  3,  2,  9, 77, 45, 33])

In [30]:
array_1d[::2]

array([ 1,  7,  3,  9, 45])

In [31]:
array_1d[1::]

array([ 5,  7,  4,  3,  2,  9, 77, 45, 33])

In [32]:
array_1d[1::2]

array([ 5,  4,  2, 77, 33])

In [33]:
array_1d[1::3]

array([ 5,  3, 77])

In [34]:
array_1d[0:5:2]

array([1, 7, 3])

In [35]:
array_1d[::3]

array([ 1,  4,  9, 33])

In [36]:
array_1d[0:9:2]

array([ 1,  7,  3,  9, 45])

In [37]:
array_2d[2]

array([11,  5, 67])

In [38]:
array_2d

array([[ 1,  3,  5],
       [ 2,  8,  6],
       [11,  5, 67],
       [ 7,  8,  5]])

In [39]:
array_2d[::2]

array([[ 1,  3,  5],
       [11,  5, 67]])

In [40]:
array_2d[:,:]

array([[ 1,  3,  5],
       [ 2,  8,  6],
       [11,  5, 67],
       [ 7,  8,  5]])

In [42]:
array_2d[::2,::2]

array([[ 1,  5],
       [11, 67]])

In [43]:
array_2d[:,1::2]

array([[3],
       [8],
       [5],
       [8]])

In [47]:
array_2d[::,::]

array([[ 1,  3,  5],
       [ 2,  8,  6],
       [11,  5, 67],
       [ 7,  8,  5]])

In [48]:
array_2d=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[22,23,24,26,27,29]])
array_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [22, 23, 24, 26, 27, 29]])

In [49]:
array_2d[:,::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [22, 24, 27]])

# max(),min(),argmax(),argmin()

In [50]:
array_ranint=np.random.randint(0,500,15)
array_ranint

array([179, 328, 451, 399, 159, 296, 273, 205,  16, 298,  93, 199, 377,
       491, 207])

In [51]:
array_ranint.max()

491

In [52]:
array_ranint.min()

16

In [53]:
array_ranint.argmax() # return index where max value is located

13

In [54]:
array_ranint.argmin() #return index where min value is located

8